### PR TITLE
fix: track the visited structures in the `checkStruct` function

### LINKED ISSUE #16: Stack overflow with v0.4.4
musttag 0.4.4 is experiencing a stack overflow when run on one of our projects. I can't share that project unfortunately but the output of `musttag ./...` is provided in the attached [file](https://github.com/junk1tm/musttag/files/10673974/stack_overflow.txt).

The problem doesn't occur if I revert this change: https://github.com/junk1tm/musttag/commit/92290849d571de15c0a625f7fc417ee0ca36f6c4#diff-cfb5a4e47e6f8c71c0c2f50fffec7a51b18984f95177a9c1af9c436475810a99R209-R213

I added some logging at it seems to be looping over some structs from [go-github](https://github.com/google/go-github).

I'm out of time to look at this for now but thought I'd let you know what I've found so far in case the problem/solution is obvious to you.

### PR DESCRIPTION
**Pull request by SVilgelm**
fix #16 with stack overflow issue when a struct has the fields of self type

### CODE REVIEW

File: testdata/src/tests/tests.go [hunk 1]
```diff
@@ -468,3 +468,14 @@ func nonStructArgument() {
 	custom.Marshal(0)
 	custom.Unmarshal(nil, &[]int{})
 }
+
+// test for stack overflow issue: https://github.com/junk1tm/musttag/issues/16
+func selfType() {
```
Comment (SVilgelm) [inline testdata/src/tests/tests.go:473]: author note: the test fails on main branch with stack overflow panic.

**Review by junk1tm — APPROVED** [review]
Awesome, thank you Sergey!
